# -*- coding: utf-8 -*-
"""Yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWLH-xFRWWo3PR7kfVn2DRn2C7vam0hn
"""

# Commented out IPython magic to ensure Python compatibility.
# 1️⃣ Clone the official YOLOv8 (Ultralytics) repo
!git clone https://github.com/ultralytics/ultralytics.git

# 2️⃣ Change directory to the cloned repo
# %cd ultralytics

# 3️⃣ Install the requirements
!pip install -r requirements.txt

from ultralytics import YOLO
model = YOLO('yolov5s.pt')

path='/content/yolo_test_image.jpg'
results = model(path)

!pip3 install pillow

from PIL import Image
import io
import base64

def plot_results(image_path,results):
  img=Image.open(image_path)
  plt.figure(figsize=(12,8))
  plt.imshow(img)

  ax=plt.gca()
  # plot each boundary box
  for result in results:
    boxes=result.boxes.xyxy
    for box in boxes:
      x1,y1,x2,y2=box
      w,h=x2-x1,y2-y1
      rect=Rectangle((x1,y1),w,h,fill=False,color='red',linewidth=2)
      ax.add_patch(rect)
plot_results(path,results)